# Generated by Django 4.1.3 on 2022-12-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название кнопки')),
                ('link', models.URLField(blank=True, max_length=2048, verbose_name='Ссылка на материал')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='RandomText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Рандомный текст')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.PositiveSmallIntegerField(choices=[(0, 'Текст'), (1, 'Аудио'), (2, 'Видео'), (3, 'Фото')], verbose_name='Тип материала')),
                ('file_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на файл (аудио, видео, фото)')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID файла в telegram')),
                ('text', models.TextField(blank=True, verbose_name='Текстовый материал')),
                ('order_of_send', models.SmallIntegerField(default=50, verbose_name='Порядок отправки')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.button', verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['order_of_send'],
            },
        ),
        migrations.CreateModel(
            name='ButtonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content.button', verbose_name='Кнопка')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
