# Generated by Django 4.1.3 on 2022-12-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttonlog',
            options={'ordering': ['-created'], 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='randomtext',
            options={'verbose_name': 'Рандомный текст', 'verbose_name_plural': 'Рандомные тексты'},
        ),
        migrations.AddField(
            model_name='button',
            name='random_text',
            field=models.BooleanField(default=False, verbose_name='Выдача рандомного текста'),
        ),
    ]
