version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:15-alpine
    env_file:
      - ../boilerplate_bot/boilerplate_bot/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    build:
      context: ../
      dockerfile: ./infra/backend/Dockerfile
    env_file:
      - ../boilerplate_bot/boilerplate_bot/.env
    volumes:
      - ../boilerplate_bot:/code
      - static_value:/code/static/
      - media_value:/code/media/
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx/config/nginx_local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  bot:
    build:
      context: ../
      dockerfile: ./infra/bot/DockerFile
    env_file:
      - ../bot/.env
    volumes:
      - ../bot:/app
